### PR TITLE
update python and dependencies

### PR DESCRIPTION
**Pull request by zganger**
-updates python to current version (performance and security improvements)
-updates dependencies
   - began with test dependencies and jupyter
   - cascaded downwards & conflicts

### CODE REVIEW

**Comment by DMalone87** [comment]
Seeing some issues on the backend.
```
api-1  | Error: While importing 'app.backend.api', an ImportError was raised:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
api-1  |     __import__(module_name)
api-1  |   File "/app/backend/api.py", line 8, in <module>
api-1  |     from backend.database import db
api-1  |   File "/app/backend/database/__init__.py", line 2, in <module>
api-1  |     from backend.database.core import db
api-1  |   File "/app/backend/database/core.py", line 12, in <module>
api-1  |     import psycopg
api-1  | ModuleNotFoundError: No module named 'psycopg'
api-1  | 
api-1  | 
api-1  | Usage: flask [OPTIONS] COMMAND [ARGS]...
api-1  | Try 'flask --help' for help.
api-1  | 
api-1  | Error: No such command 'psql'.
web-1  | info  - Using external babel configuration from /app/babel.config.js
api-1  | Error: While importing 'app.backend.api', an ImportError was raised:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
api-1  |     __import__(module_name)
api-1  |   File "/app/backend/api.py", line 8, in <module>
api-1  |     from backend.database import db
api-1  |   File "/app/backend/database/__init__.py", line 2, in <module>
api-1  |     from backend.database.core import db
api-1  |   File "/app/backend/database/core.py", line 12, in <module>
api-1  |     import psycopg
api-1  | ModuleNotFoundError: No module named 'psycopg'
api-1  | 
api-1  | 
api-1  | Usage: flask [OPTIONS] COMMAND [ARGS]...
api-1  | Try 'flask --help' for help.
api-1  | 
api-1  | Error: No such command 'psql'.
api-1  | Usage: flask db seed [OPTIONS]
api-1  | 
api-1  | Error: While importing 'app.backend.api', an ImportError was raised:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
api-1  |     __import__(module_name)
api-1  |   File "/app/backend/api.py", line 8, in <module>
api-1  |     from backend.database import db
api-1  |   File "/app/backend/database/__init__.py", line 2, in <module>
api-1  |     from backend.database.core import db
api-1  |   File "/app/backend/database/core.py", line 12, in <module>
api-1  |     import psycopg
api-1  | ModuleNotFoundError: No module named 'psycopg'
api-1  | 
api-1  |  * Serving Flask app 'backend.api:create_app()' (lazy loading)
api-1  |  * Environment: development
api-1  |  * Debug mode: on
api-1  | Usage: flask run [OPTIONS]
api-1  | 
api-1  | Error: While importing 'app.backend.api', an ImportError was raised:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
api-1  |     __import__(module_name)
api-1  |   File "/app/backend/api.py", line 8, in <module>
api-1  |     from backend.database import db
api-1  |   File "/app/backend/database/__init__.py", line 2, in <module>
api-1  |     from backend.database.core import db
api-1  |   File "/app/backend/database/core.py", line 12, in <module>
api-1  |     import psycopg
api-1  | ModuleNotFoundError: No module named 'psycopg'
api-1  | 
api-1 exited with code 2
```

**Comment by zganger** [comment]
Thanks @DMalone87, I added `psycopg` v3.1.18 to the dependencies.

**Comment by zganger** [comment]
I had to run the following since I had run docker-compose before and had leftover artifacts that conflicted, in case you hit errors with Postgres container failing to boot.

```
$ docker stop $(docker container ls -aq)
$ echo 'y' | docker system prune
$ docker volume rm police-data-trust_postgres
```

**Comment by DMalone87** [comment]
So, it appears to be properly set in the requirements, but it's not getting installed successfully for me.
```
3.339   Downloading iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
3.399 Collecting ipykernel==6.29.2 (from -r requirements/dev_unix.txt (line 134))
3.399   Obtaining dependency information for ipykernel==6.29.2 from https://files.pythonhosted.org/packages/16/9a/0c7b514c73b42cf4ce516ee26c8940a0b23a9754dafaa459a939220240fd/ipykernel-6.29.2-py3-none-any.whl.metadata
3.413   Downloading ipykernel-6.29.2-py3-none-any.whl.metadata (6.0 kB)
3.457 ERROR: Ignored the following versions that require a different python version: 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10
3.457 ERROR: Could not find a version that satisfies the requirement ipython==8.22.1 (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1, 7.16.2, 7.16.3, 7.17.0, 7.18.0, 7.18.1, 7.19.0, 7.20.0, 7.21.0, 7.22.0, 7.23.0, 7.23.1, 7.24.0, 7.24.1, 7.25.0, 7.26.0, 7.27.0, 7.28.0, 7.29.0, 7.30.0, 7.30.1, 7.31.0, 7.31.1, 7.32.0, 7.33.0, 7.34.0, 8.0.0a1, 8.0.0b1, 8.0.0rc1, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.2.0, 8.3.0, 8.4.0, 8.5.0, 8.6.0, 8.7.0, 8.8.0, 8.9.0, 8.10.0, 8.11.0, 8.12.0, 8.12.1, 8.12.2, 8.12.3, 8.13.0, 8.13.1, 8.13.2, 8.14.0, 8.15.0, 8.16.0, 8.16.1, 8.17.0, 8.17.1, 8.17.2, 8.18.0, 8.18.1)
3.457 ERROR: No matching distribution found for ipython==8.22.1
3.576 
3.576 [notice] A new release of pip is available: 23.2 -> 24.0
3.576 [notice] To update, run: pip install --upgrade pip
```

The installation of reqs gets halted here.

**Comment by mikeyavorsky** [comment]
For Apple Silicon Mac, need to
```
brew install postgresql
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib -L${HOME}/.pyenv/versions/3.8.10/lib"

```

**Comment by zganger** [comment]
@DMalone87 which version of python are you using to attempt to install? Note the version is updated with this changeset- the warning is telling you to use python > 3.10. Here we use 3.12 for docker images.

**Comment by zganger** [comment]
Rebased successfully. https://github.com/codeforboston/Police-Data-Trust-Infrastructure/pull/2 is the infrastructure update to match the dockerized changes here.

**Review by DMalone87 — APPROVED** [review]

**Pull request merged**
