### PR TITLE
feat218: implement search form functionality part 1

### PR DESCRIPTION
**Pull request by srsexton94**
Does UI fixes to set up form implementation - consolidates/removes duplicate components, implements form toggle box, fixes general layout pre & post search submission

Still need to address erroneous form validation, datepicker bugs, and actually implement form submission

### CODE REVIEW

**Comment by srsexton94** [comment]
Woops, didn't realize we'd added tests - will fix

**Review by sashamaryl — APPROVED** [review]

**Review by JMStudiosJoe — DISMISSED** [review]
looking great so far is it ready to be merged?

**Review by sashamaryl — DISMISSED** [review]
LGTM! Yeah, I think my outstanding PR has the fixes for these failing tests, which did exist on the main branch before. Let's merge!

**Comment by JMStudiosJoe** [comment]
can we resolve the conflicts then merge?

**Comment by DMalone87** [comment]
These errors are from an existing error that was merged previously.

**Pull request merged**
