### PR TITLE
Epic 2 UI: My Organizations user table, Inviting new users (fixed package.json)

### PR DESCRIPTION
**Pull request by yuwatidora**

### CODE REVIEW

**Comment by DMalone87** [comment]
I'm getting a crash on the front end here:
```web-1  | 
web-1  | > pdc@0.1.0 dev
web-1  | > NODE_OPTIONS='--openssl-legacy-provider' next dev
web-1  | 
web-1  | node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
web-1 exited with code 9
```

**Comment by yuwatidora** [comment]
> I'm getting a crash on the front end here:
> 
> ```
> web-1  | > pdc@0.1.0 dev
> web-1  | > NODE_OPTIONS='--openssl-legacy-provider' next dev
> web-1  | 
> web-1  | node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
> web-1 exited with code 9
> ```

Hi Darrell, I removed openssl-legacy-provider from package.json in this pull request. I am sorry, but I am unsure why it has not been updated when you try to run it.

**Comment by DMalone87** [comment]
Ahh, OK. You may need to rebuild the requirements then. Let me see if that fixes it.

**Review by DMalone87 — APPROVED** [review]
Looks good!

**Comment by DMalone87** [comment]
My mistake, @yuwatidora > It was just a fetching error. You're good to go!

**Comment by DMalone87** [comment]
Merged in #365

**Pull request closed without merging**
