### PR TITLE
fix(deploy): Remove the 3rd party action; use Heroku CLI directly

### LINKED ISSUE #67: [BUG] Remove 3rd party GitHub action for heroku deploy
**Describe the bug**
The current heroku.yml workflow is designed to use a 3rd party (unverified) action for deployment to Heroku. This project leverages Heroku's new Platform API and container registry. 

https://github.com/codeforboston/police-data-trust/blob/3a425195be46379f2ca49e7159a39801e23ae33f/.github/workflows/heroku.yml#L13

Code for Boston has not been able to deploy this app successfully using this action.  We have not been able to get this action to authenticate with Heroku successfully.

**To Reproduce**
1. Merge any Pull Request into `main`
2. Look at the Actions tab

**Expected behavior**
When you merge into `main`, the action should at least successfully authenticate with Heroku and attempt to push a container with the latest app build.

**Additional context**
Using this 3rd party action should not be necessary given that the Heroku CLI comes preinstalled in Ubuntu images. [See supported software](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)

### PR DESCRIPTION
**Pull request by jcockhren**
This Pull Request attempts to use the Heroku CLI directly b/c it's comes preinstalled on the Ubuntu 20.04 image.

See: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

closes #67

### CODE REVIEW

**Comment by JMStudiosJoe** [comment]
can you update the PR base branch please? Also I think we will be moving towards AWS deployments @DMalone87 were you able to confirm that?

**Comment by DMalone87** [comment]
Yes, correct

**Comment by jcockhren** [comment]
I may have misunderstood what you were asking me @DMalone87. I thought it the move to AWS ahead of MVP completion was due to the deploys being broken. Or are there other reasons?

You all want to abandon this PR if it fixes Heroku deploy today?

**Comment by jcockhren** [comment]
> can you update the PR base branch please? Also I think we will be moving towards AWS deployments @DMalone87 were you able to confirm that?

@JMStudiosJoe Re: PR base branch. I'm not sure what you're asking. This is a PR from a fork into the `main` branch of this repo.

**Comment by DMalone87** [comment]
> > can you update the PR base branch please? Also I think we will be moving towards AWS deployments @DMalone87 were you able to confirm that?
> 
> @JMStudiosJoe Re: PR base branch. This is a PR from a branch on a fork into the `main` branch of this repo. Should this PR not be merged into `main`?

Just removed the update requirement so no issues there.

As for AWS, it was more overall compatibility that was the issue.

**Review by DMalone87 — APPROVED** [review]
Let's get this up and see if we can get it running on Heroku. We can do the AWS migration at a later date if needed.

**Pull request merged**
